//! Marketplace: one-click apps & stacks (§6.8, docs/SPEC.md). Users pick a
//! curated catalog item (an app.json + compose.yml pair), the backend
//! renders variable values (passwords, ports, etc.) into a compose project
//! under `<app_data_dir>/marketplace/<profile>/<projectName>/`, brings it up
//! with `docker compose` (reusing `compose.rs`'s mode resolution/streaming),
//! waits for the declared readiness condition, and returns rendered
//! endpoints (URLs/credentials/connection strings).
//!
//! The built-in catalog is embedded at compile time from
//! `catalog/dist/catalog.json` (generated by `npm run catalog:build`; see
//! `catalog/README.md`). A remote copy is fetched from GitHub and cached on
//! disk for 6h (same shape as `k3s.rs`'s version cache), falling back to a
//! stale cache on network error and finally to the built-in copy.

use crate::colima::resolve_docker_socket;
use crate::compose::{self, ComposeMode, ComposeUpOptions};
use crate::exec;
use crate::state::AppState;
use crate::validate::validate_profile_name;
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use std::io::Write;
use std::net::TcpListener;
use std::path::{Path, PathBuf};
use std::time::Duration;
use tauri::{AppHandle, Emitter, Manager, State};

// ---------------------------------------------------------------------------
// Catalog types (mirror `catalog/schema.json` / app.json, §6.8)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CatalogSource {
    pub name: String,
    pub url: String,
    pub license: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CatalogVariable {
    pub name: String,
    #[serde(rename = "type")]
    pub var_type: String, // "password" | "port" | "string"
    #[serde(default)]
    pub label: Option<String>,
    #[serde(default)]
    pub length: Option<u32>,
    #[serde(default)]
    pub default: Option<serde_json::Value>,
    #[serde(default)]
    pub hidden: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CatalogEndpoint {
    pub name: String,
    #[serde(default)]
    pub url: Option<String>,
    #[serde(default)]
    pub value: Option<String>,
    #[serde(default)]
    pub username: Option<String>,
    #[serde(default)]
    pub password: Option<String>,
    #[serde(default)]
    pub primary: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CatalogPreflightCheck {
    #[serde(rename = "sysctl", rename_all = "camelCase")]
    Sysctl { key: String, min: i64 },
}

// NB: `rename_all` at the enum level does NOT propagate into internally
// tagged (`tag = "type"`) variants' own fields in this serde version — each
// variant needs its own `rename_all = "camelCase"` (verified: without it,
// `expectStatus`/`timeoutSec` silently fail to deserialize and fall back to
// their `#[serde(default = ...)]` values instead of erroring, which would
// have been a very easy bug to miss without the wire-format test below).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CatalogReady {
    #[serde(rename = "http", rename_all = "camelCase")]
    Http {
        url: String,
        #[serde(default = "default_expect_status")]
        expect_status: Vec<u16>,
        #[serde(default = "default_ready_timeout")]
        timeout_sec: u64,
    },
    #[serde(rename = "healthy", rename_all = "camelCase")]
    Healthy {
        #[serde(default = "default_ready_timeout")]
        timeout_sec: u64,
    },
    #[serde(rename = "running", rename_all = "camelCase")]
    Running {
        #[serde(default = "default_ready_timeout")]
        timeout_sec: u64,
    },
}

fn default_expect_status() -> Vec<u16> {
    vec![200]
}

fn default_ready_timeout() -> u64 {
    120
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CatalogItem {
    pub id: String,
    pub name: String,
    pub description: String,
    pub category: String,
    #[serde(default)]
    pub tags: Vec<String>,
    #[serde(default)]
    pub icon: Option<String>,
    #[serde(default)]
    pub website: Option<String>,
    #[serde(default)]
    pub source: Option<CatalogSource>,
    #[serde(default)]
    pub architectures: Vec<String>,
    // NB: `rename_all = "camelCase"` would produce `minMemoryMb` (serde
    // doesn't know "MB" is an acronym) — the frontend type is `minMemoryMB`,
    // so this field needs an explicit rename.
    #[serde(default, rename = "minMemoryMB")]
    pub min_memory_mb: Option<u64>,
    #[serde(default)]
    pub variables: Vec<CatalogVariable>,
    #[serde(default)]
    pub endpoints: Vec<CatalogEndpoint>,
    #[serde(default)]
    pub preflight: Vec<CatalogPreflightCheck>,
    #[serde(default)]
    pub ready: Option<CatalogReady>,
    #[serde(default)]
    pub notes: Option<String>,
    /// The compose.yml text — present in `dist/catalog.json` entries, absent
    /// from `app.json` alone. Defaulted to empty so `#[serde(default)]`
    /// tolerant parsing never fails on this field; validated (non-empty)
    /// wherever an item is actually installed.
    #[serde(default)]
    pub compose: String,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MarketplaceCatalogResponse {
    pub items: Vec<CatalogItem>,
    pub source: CatalogSourceKind,
    pub fetched_at: Option<String>,
    pub error: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum CatalogSourceKind {
    Remote,
    Cache,
    Builtin,
}

#[derive(Debug, Deserialize)]
struct CatalogFile {
    #[serde(rename = "schemaVersion")]
    schema_version: u32,
    #[serde(default)]
    #[allow(dead_code)]
    generated_at: String,
    items: Vec<CatalogItem>,
}

const BUILTIN_CATALOG_JSON: &str = include_str!("../../catalog/dist/catalog.json");
const SUPPORTED_SCHEMA_VERSION: u32 = 1;
const REMOTE_CATALOG_URL: &str =
    "https://raw.githubusercontent.com/alperen-selcuk/colima-desktop/main/catalog/dist/catalog.json";
const CATALOG_CACHE_FILE_NAME: &str = "marketplace-catalog.json";
const CATALOG_CACHE_TTL: Duration = Duration::from_secs(6 * 60 * 60);
const CATALOG_FETCH_TIMEOUT: Duration = Duration::from_secs(10);
const USER_AGENT: &str = "colima-desktop";

/// Parse+validate a catalog JSON document's schema version, returning its
/// items on success. `None` when the schema version isn't one this build
/// understands (§6.8: "ignore remote with a different schemaVersion").
fn parse_catalog(content: &str) -> Option<Vec<CatalogItem>> {
    let parsed: CatalogFile = serde_json::from_str(content).ok()?;
    if parsed.schema_version != SUPPORTED_SCHEMA_VERSION {
        return None;
    }
    Some(parsed.items)
}

fn builtin_catalog_items() -> Vec<CatalogItem> {
    parse_catalog(BUILTIN_CATALOG_JSON).unwrap_or_default()
}

fn catalog_cache_path(app: &AppHandle) -> Option<PathBuf> {
    app.path().app_cache_dir().ok().map(|d| d.join(CATALOG_CACHE_FILE_NAME))
}

#[derive(Debug, Serialize, Deserialize)]
struct CatalogDiskCache {
    fetched_at_unix: u64,
    raw: String,
}

fn read_catalog_cache(app: &AppHandle) -> Option<(String, std::time::SystemTime)> {
    let path = catalog_cache_path(app)?;
    let content = std::fs::read_to_string(path).ok()?;
    let cache: CatalogDiskCache = serde_json::from_str(&content).ok()?;
    let at = std::time::UNIX_EPOCH + Duration::from_secs(cache.fetched_at_unix);
    Some((cache.raw, at))
}

fn write_catalog_cache(app: &AppHandle, raw: &str) {
    let Some(path) = catalog_cache_path(app) else { return };
    if let Some(dir) = path.parent() {
        let _ = std::fs::create_dir_all(dir);
    }
    let fetched_at_unix = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let cache = CatalogDiskCache { fetched_at_unix, raw: raw.to_string() };
    if let Ok(json) = serde_json::to_string(&cache) {
        let _ = std::fs::write(path, json);
    }
}

fn cache_is_fresh(now: std::time::SystemTime, cached_at: std::time::SystemTime) -> bool {
    match now.duration_since(cached_at) {
        Ok(age) => age < CATALOG_CACHE_TTL,
        Err(_) => true,
    }
}

async fn fetch_remote_catalog() -> Result<String, String> {
    let client = reqwest::Client::builder()
        .timeout(CATALOG_FETCH_TIMEOUT)
        .user_agent(USER_AGENT)
        .build()
        .map_err(|e| e.to_string())?;
    let resp = client.get(REMOTE_CATALOG_URL).send().await.map_err(|e| e.to_string())?;
    if !resp.status().is_success() {
        return Err(format!("catalog fetch returned {}", resp.status()));
    }
    resp.text().await.map_err(|e| e.to_string())
}

fn iso_now() -> String {
    let unix = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    format!("{unix}") // callers only display fetchedAt; keep this simple/pure
}

#[tauri::command]
pub async fn marketplace_catalog(app: AppHandle, force_refresh: bool) -> Result<MarketplaceCatalogResponse, String> {
    let cached = read_catalog_cache(&app);
    let now = std::time::SystemTime::now();

    if !force_refresh {
        if let Some((raw, cached_at)) = &cached {
            if cache_is_fresh(now, *cached_at) {
                if let Some(items) = parse_catalog(raw) {
                    return Ok(MarketplaceCatalogResponse {
                        items,
                        source: CatalogSourceKind::Cache,
                        fetched_at: Some(iso_now()),
                        error: None,
                    });
                }
            }
        }
    }

    match fetch_remote_catalog().await {
        Ok(raw) => match parse_catalog(&raw) {
            Some(items) => {
                write_catalog_cache(&app, &raw);
                Ok(MarketplaceCatalogResponse {
                    items,
                    source: CatalogSourceKind::Remote,
                    fetched_at: Some(iso_now()),
                    error: None,
                })
            }
            None => {
                // Different/unsupported schema version or malformed body:
                // ignore the remote payload per §6.8 and fall through to
                // cache/builtin below.
                serve_stale_or_builtin(cached, Some("remote catalog schema version not supported".to_string()))
            }
        },
        Err(fetch_err) => serve_stale_or_builtin(cached, Some(fetch_err)),
    }
}

fn serve_stale_or_builtin(
    cached: Option<(String, std::time::SystemTime)>,
    error: Option<String>,
) -> Result<MarketplaceCatalogResponse, String> {
    if let Some((raw, _cached_at)) = cached {
        if let Some(items) = parse_catalog(&raw) {
            return Ok(MarketplaceCatalogResponse {
                items,
                source: CatalogSourceKind::Cache,
                fetched_at: Some(iso_now()),
                error,
            });
        }
    }
    Ok(MarketplaceCatalogResponse {
        items: builtin_catalog_items(),
        source: CatalogSourceKind::Builtin,
        fetched_at: None,
        error,
    })
}

/// Look up one catalog item by id, using the same fetch/cache/builtin
/// resolution as `marketplace_catalog` (never force-refreshing, since the
/// caller just wants the currently-known item).
async fn find_catalog_item(app: &AppHandle, item_id: &str) -> Result<CatalogItem, String> {
    let resp = marketplace_catalog(app.clone(), false).await?;
    resp.items
        .into_iter()
        .find(|i| i.id == item_id)
        .ok_or_else(|| format!("unknown marketplace item: {item_id}"))
}

// ---------------------------------------------------------------------------
// Instance storage types
// ---------------------------------------------------------------------------

/// `<app_data_dir>/marketplace/<profile>/<projectName>/instance.json`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InstanceManifest {
    pub item_id: String,
    pub name: String,
    pub icon: Option<String>,
    pub project_name: String,
    pub created_at: String,
    pub catalog_generated_at: String,
    pub values: HashMap<String, String>,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct RenderedVariable {
    pub name: String,
    pub label: String,
    #[serde(rename = "type")]
    pub var_type: String,
    pub value: String,
    pub hidden: bool,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PreflightResult {
    pub id: String,
    pub ok: bool,
    pub severity: String, // "error" | "warning"
    pub message: String,
    pub fixable: bool,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MarketplacePrepareResponse {
    pub project_name: String,
    pub variables: Vec<RenderedVariable>,
    pub preflight: Vec<PreflightResult>,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct InstalledEndpoint {
    pub name: String,
    pub url: Option<String>,
    pub value: Option<String>,
    pub username: Option<String>,
    pub password: Option<String>,
    pub primary: bool,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct InstalledApp {
    pub project_name: String,
    pub item_id: String,
    pub name: String,
    pub icon: Option<String>,
    pub created_at: String,
    pub status: String,
    pub endpoints: Vec<InstalledEndpoint>,
    pub notes: Option<String>,
}

// ---------------------------------------------------------------------------
// Pure helpers (unit tested)
// ---------------------------------------------------------------------------

/// Validate a marketplace item id: `^[a-z0-9][a-z0-9-]*$` (§6.8's app.json
/// `id` rule).
pub fn is_valid_item_id(id: &str) -> bool {
    if id.is_empty() {
        return false;
    }
    let mut chars = id.chars();
    let first = chars.next().unwrap();
    if !(first.is_ascii_lowercase() || first.is_ascii_digit()) {
        return false;
    }
    chars.all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
}

pub fn validate_item_id(id: &str) -> Result<(), String> {
    if is_valid_item_id(id) {
        Ok(())
    } else {
        Err(format!("invalid marketplace item id: {id:?}"))
    }
}

/// Default project name for an item: `cd-<id>`, suffixed `-2`, `-3`, … if
/// taken (compared against `taken`, e.g. existing instance dirs).
pub fn default_project_name(item_id: &str, taken: &HashSet<String>) -> String {
    let base = format!("cd-{item_id}");
    if !taken.contains(&base) {
        return base;
    }
    let mut n = 2u32;
    loop {
        let candidate = format!("{base}-{n}");
        if !taken.contains(&candidate) {
            return candidate;
        }
        n += 1;
    }
}

/// Substitute `${VAR}` placeholders in `template` from `values`. Unknown
/// variables are left as-is (not substituted) rather than erroring, since
/// endpoint/ready templates are trusted catalog content, not user input.
pub fn render_template(template: &str, values: &HashMap<String, String>) -> String {
    let mut out = String::with_capacity(template.len());
    let bytes = template.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'$' && i + 1 < bytes.len() && bytes[i + 1] == b'{' {
            if let Some(end) = template[i + 2..].find('}') {
                let var_name = &template[i + 2..i + 2 + end];
                if let Some(value) = values.get(var_name) {
                    out.push_str(value);
                } else {
                    out.push_str(&template[i..i + 2 + end + 1]);
                }
                i += 2 + end + 1;
                continue;
            }
        }
        // Push one char (handling multi-byte UTF-8 correctly).
        let ch = template[i..].chars().next().unwrap();
        out.push(ch);
        i += ch.len_utf8();
    }
    out
}

/// CSPRNG alphanumeric password of `length` characters (mixed-case letters +
/// digits; URL/YAML-safe per §6.8's "Passwords alphanumeric" rule).
pub fn generate_password(length: u32) -> String {
    const ALPHABET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let len = length.max(1) as usize;
    let mut bytes = vec![0u8; len];
    getrandom::getrandom(&mut bytes).expect("system CSPRNG must be available");
    bytes.iter().map(|b| ALPHABET[(*b as usize) % ALPHABET.len()] as char).collect()
}

/// Whether `port` is free: not present in `taken` (the union of host-bound
/// TCP listeners on 127.0.0.1/0.0.0.0, docker-published ports, and ports
/// reserved by other marketplace instances' `.env` files — the caller
/// assembles `taken` via [`collect_taken_ports`] / a live bind test).
pub fn is_port_free(port: u16, taken: &HashSet<u16>) -> bool {
    !taken.contains(&port)
}

/// Live bind test: true if `port` can be bound on both 127.0.0.1 and
/// 0.0.0.0 (i.e. genuinely free at the OS level right now).
fn port_bind_free(port: u16) -> bool {
    TcpListener::bind(("127.0.0.1", port)).is_ok() && TcpListener::bind(("0.0.0.0", port)).is_ok()
}

/// Extract host-bound TCP ports already used by other marketplace instances
/// from their `.env` files: any `KEY=VALUE` line whose value parses as a
/// bare u16, for every instance dir under `<profile_dir>` except
/// `exclude_project` (the instance currently being prepared/re-saved, if
/// any).
fn ports_reserved_by_other_instances(profile_dir: &Path, exclude_project: Option<&str>) -> HashSet<u16> {
    let mut ports = HashSet::new();
    let Ok(entries) = std::fs::read_dir(profile_dir) else {
        return ports;
    };
    for entry in entries.flatten() {
        let Ok(file_type) = entry.file_type() else { continue };
        if !file_type.is_dir() {
            continue;
        }
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if Some(name.as_ref()) == exclude_project {
            continue;
        }
        let env_path = entry.path().join(".env");
        let Ok(content) = std::fs::read_to_string(&env_path) else { continue };
        for (_k, v) in parse_env_lines(&content) {
            if let Ok(p) = v.parse::<u16>() {
                ports.insert(p);
            }
        }
    }
    ports
}

/// Resolve the requested/default port for a `port`-typed variable to an
/// actually-free port: prefer the requested default; if taken, scan upward.
/// `taken` should already include reserved-by-other-instances and
/// docker-published ports; this also live-bind-tests each candidate so a
/// port free on disk-state but held by some unrelated process is skipped.
fn resolve_free_port(default: u16, taken: &HashSet<u16>) -> u16 {
    let mut candidate = default;
    loop {
        if is_port_free(candidate, taken) && port_bind_free(candidate) {
            return candidate;
        }
        candidate = candidate.saturating_add(1);
        if candidate == 0 {
            // wrapped (started at 65535); give up and return the original
            // default rather than looping forever.
            return default;
        }
    }
}

/// Parse simple `KEY=VALUE` lines from an `.env`-style file (one per line,
/// `#`-prefixed/blank lines skipped, values may be double-quoted). Used both
/// to scan reserved ports and, in tests, to verify serialisation round-trips.
pub fn parse_env_lines(content: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((k, v)) = line.split_once('=') else { continue };
        let v = v.trim();
        let v = if v.len() >= 2 && v.starts_with('"') && v.ends_with('"') {
            unescape_env_value(&v[1..v.len() - 1])
        } else {
            v.to_string()
        };
        out.push((k.trim().to_string(), v));
    }
    out
}

fn unescape_env_value(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars();
    while let Some(c) = chars.next() {
        if c == '\\' {
            match chars.next() {
                Some('"') => out.push('"'),
                Some('\\') => out.push('\\'),
                Some('n') => out.push('\n'),
                Some(other) => {
                    out.push('\\');
                    out.push(other);
                }
                None => out.push('\\'),
            }
        } else {
            out.push(c);
        }
    }
    out
}

/// Escape one value for a double-quoted `.env` line: backslash then quote
/// characters escaped, embedded newlines escaped, so the file round-trips
/// through both this parser and docker compose's own `.env` reader (which
/// also honors double-quoted values with the same two escapes).
fn escape_env_value(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for c in value.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            other => out.push(other),
        }
    }
    out
}

/// Serialise an ordered list of `(key, value)` pairs into `.env` file
/// content: one `KEY="escaped value"` line per pair, trailing newline. Every
/// value is double-quoted so blank/special-character values are unambiguous.
pub fn serialize_env_file(pairs: &[(String, String)]) -> String {
    let mut out = String::new();
    for (k, v) in pairs {
        out.push_str(k);
        out.push_str("=\"");
        out.push_str(&escape_env_value(v));
        out.push_str("\"\n");
    }
    out
}

/// Validate a sysctl key against `^[a-z0-9_.]+$` (§6.8's fix-preflight rule:
/// keys/values come from the catalog but must be validated before building
/// an in-VM shell command).
pub fn is_valid_sysctl_key(key: &str) -> bool {
    !key.is_empty() && key.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_' || c == '.')
}

/// Validate a sysctl value: digits only (every catalog sysctl check today is
/// an integer minimum; keeping this strict avoids ever building a shell
/// command from an unvalidated string).
pub fn is_valid_sysctl_value(value: &str) -> bool {
    !value.is_empty() && value.chars().all(|c| c.is_ascii_digit())
}

/// Parsed `colima status --json` arch string, mapped to catalog
/// architecture ids (§6.8: `aarch64`->`arm64`, `x86_64`->`amd64`).
pub fn normalize_arch(colima_arch: &str) -> String {
    match colima_arch {
        "aarch64" => "arm64".to_string(),
        "x86_64" => "amd64".to_string(),
        other => other.to_string(),
    }
}

/// Evaluate the `arch` preflight check: error if `architectures` is
/// non-empty and doesn't contain the normalized VM arch.
pub fn evaluate_arch_preflight(vm_arch: &str, architectures: &[String]) -> PreflightResult {
    let normalized = normalize_arch(vm_arch);
    let ok = architectures.is_empty() || architectures.iter().any(|a| a == &normalized);
    PreflightResult {
        id: "arch".to_string(),
        ok,
        severity: "error".to_string(),
        message: if ok {
            format!("architecture {normalized} is supported")
        } else {
            format!("this app supports {} but the machine is {normalized}", architectures.join(", "))
        },
        fixable: false,
    }
}

/// Evaluate the `memory` preflight check: warning if VM memory (bytes) is
/// below `min_memory_mb`.
pub fn evaluate_memory_preflight(vm_memory_bytes: u64, min_memory_mb: Option<u64>) -> Option<PreflightResult> {
    let min_mb = min_memory_mb?;
    let vm_mb = vm_memory_bytes / (1024 * 1024);
    let ok = vm_mb >= min_mb;
    Some(PreflightResult {
        id: "memory".to_string(),
        ok,
        severity: "warning".to_string(),
        message: if ok {
            format!("{vm_mb} MiB available (recommended {min_mb} MiB)")
        } else {
            format!("machine has {vm_mb} MiB; {min_mb} MiB recommended for this app")
        },
        fixable: false,
    })
}

/// Evaluate one `sysctl` preflight check from a value already read from the
/// VM (`colima ssh -p <p> -- sysctl -n <key>`); `current` is `None` if the
/// read failed.
pub fn evaluate_sysctl_preflight(key: &str, min: i64, current: Option<i64>) -> PreflightResult {
    let id = format!("sysctl:{key}");
    match current {
        Some(v) if v >= min => PreflightResult {
            id,
            ok: true,
            severity: "error".to_string(),
            message: format!("{key}={v} (>= {min})"),
            fixable: true,
        },
        Some(v) => PreflightResult {
            id,
            ok: false,
            severity: "error".to_string(),
            message: format!("{key}={v}, needs >= {min}"),
            fixable: true,
        },
        None => PreflightResult {
            id,
            ok: false,
            severity: "error".to_string(),
            message: format!("could not read {key} from the VM"),
            fixable: true,
        },
    }
}

/// Evaluate the `compose available` preflight check.
pub fn evaluate_compose_preflight(available: bool) -> PreflightResult {
    PreflightResult {
        id: "compose".to_string(),
        ok: available,
        severity: "error".to_string(),
        message: if available {
            "Docker Compose is available".to_string()
        } else {
            "Docker Compose is not available".to_string()
        },
        fixable: false,
    }
}

/// Whether a ready-check's HTTP status counts as "ready" (§6.8: `expectStatus`).
pub fn http_status_is_ready(status: u16, expect: &[u16]) -> bool {
    expect.contains(&status)
}

/// Parse `compose ps --format json` (JSON-lines, one object per line) health
/// values and decide if every service with a health status reports
/// `"healthy"`. Services with no `Health` field (no healthcheck defined) are
/// ignored, matching §6.8's "all services with healthchecks report healthy".
/// Returns `false` (not ready) if there is not at least one reporting a
/// health value at all AND the list is non-empty but nothing is healthy yet;
/// an empty list (no containers yet) is also not ready.
pub fn evaluate_healthy_ready(statuses: &[Option<String>]) -> bool {
    if statuses.is_empty() {
        return false;
    }
    let with_health: Vec<&String> = statuses.iter().filter_map(|s| s.as_ref()).collect();
    if with_health.is_empty() {
        // No service declares a healthcheck: "healthy" degenerates to
        // "everything is at least present", which `running`-style callers
        // handle separately; treat as ready once containers exist.
        return true;
    }
    with_health.iter().all(|s| s.as_str() == "healthy")
}

/// Validate a value for a catalog variable's declared type before it's
/// written into `.env`/rendered into a compose file: `port` must parse as
/// u16, `password`/`string` accept any non-empty (for password) or any
/// string (for string) value. Returns `Err` with a human message on
/// mismatch.
pub fn validate_variable_value(var: &CatalogVariable, value: &str) -> Result<(), String> {
    match var.var_type.as_str() {
        "port" => {
            value
                .parse::<u16>()
                .map(|_| ())
                .map_err(|_| format!("{}: must be a valid port number", var.name))?;
            Ok(())
        }
        "password" => {
            if value.is_empty() {
                return Err(format!("{}: password must not be empty", var.name));
            }
            if !value.chars().all(|c| c.is_ascii_alphanumeric()) {
                return Err(format!("{}: password must be alphanumeric", var.name));
            }
            Ok(())
        }
        "string" => Ok(()),
        other => Err(format!("{}: unknown variable type {other:?}", var.name)),
    }
}

/// Build the ordered `(key, value)` pairs to write to `.env`: every variable
/// value plus `COMPOSE_PROJECT_NAME`.
pub fn build_env_pairs(values: &HashMap<String, String>, project_name: &str, var_order: &[String]) -> Vec<(String, String)> {
    let mut pairs = Vec::with_capacity(values.len() + 1);
    for name in var_order {
        if let Some(v) = values.get(name) {
            pairs.push((name.clone(), v.clone()));
        }
    }
    // Any values not covered by var_order (shouldn't normally happen) still
    // get written, sorted for determinism.
    let mut extra: Vec<&String> = values.keys().filter(|k| !var_order.contains(k)).collect();
    extra.sort();
    for k in extra {
        pairs.push((k.clone(), values[k].clone()));
    }
    pairs.push(("COMPOSE_PROJECT_NAME".to_string(), project_name.to_string()));
    pairs
}

/// Render every declared endpoint's templated fields using `values`.
pub fn render_endpoints(endpoints: &[CatalogEndpoint], values: &HashMap<String, String>) -> Vec<InstalledEndpoint> {
    endpoints
        .iter()
        .map(|e| InstalledEndpoint {
            name: e.name.clone(),
            url: e.url.as_ref().map(|u| render_template(u, values)),
            value: e.value.as_ref().map(|v| render_template(v, values)),
            username: e.username.as_ref().map(|u| render_template(u, values)),
            password: e.password.as_ref().map(|p| render_template(p, values)),
            primary: e.primary,
        })
        .collect()
}

/// The marketplace root: `<app_data_dir>/marketplace`.
fn marketplace_root(app_data_dir: &Path) -> PathBuf {
    app_data_dir.join("marketplace")
}

/// `<marketplace_root>/<profile>`.
fn profile_marketplace_dir(app_data_dir: &Path, profile: &str) -> PathBuf {
    marketplace_root(app_data_dir).join(profile)
}

/// `<marketplace_root>/<profile>/<projectName>`.
fn instance_dir(app_data_dir: &Path, profile: &str, project_name: &str) -> PathBuf {
    profile_marketplace_dir(app_data_dir, profile).join(project_name)
}

/// Guard against path traversal: `project_name` must be a plain compose
/// project name (already validated elsewhere) and the resolved instance dir
/// must actually be inside the marketplace root for this profile. Used
/// before any destructive filesystem operation on an instance dir.
fn instance_dir_within_root(app_data_dir: &Path, profile: &str, project_name: &str) -> Result<PathBuf, String> {
    if !compose::is_valid_project_name(project_name) {
        return Err(format!("invalid project name: {project_name:?}"));
    }
    let root = profile_marketplace_dir(app_data_dir, profile);
    let dir = instance_dir(app_data_dir, profile, project_name);
    // Purely lexical containment check (the dir may not exist yet, so we
    // can't canonicalize): root is `<app_data_dir>/marketplace/<profile>`
    // and dir is always `root.join(project_name)` above, but re-verify via
    // `strip_prefix` so any future refactor can't silently break this.
    dir.strip_prefix(&root).map_err(|_| "instance path escapes the marketplace root".to_string())?;
    Ok(dir)
}

fn write_atomically(path: &Path, content: &[u8], mode: Option<u32>) -> Result<(), String> {
    let dir = path.parent().ok_or_else(|| "invalid instance path".to_string())?;
    std::fs::create_dir_all(dir).map_err(|e| format!("failed to create instance directory: {e}"))?;
    let file_name = path.file_name().ok_or_else(|| "invalid instance path".to_string())?.to_string_lossy();
    let tmp_path = dir.join(format!(".{file_name}.tmp-{}", std::process::id()));

    let result = (|| -> Result<(), String> {
        let mut file = std::fs::File::create(&tmp_path).map_err(|e| format!("failed to write file: {e}"))?;
        file.write_all(content).map_err(|e| format!("failed to write file: {e}"))?;
        file.sync_all().map_err(|e| format!("failed to write file: {e}"))?;
        #[cfg(unix)]
        if let Some(mode) = mode {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = file.metadata().map_err(|e| format!("failed to write file: {e}"))?.permissions();
            perms.set_mode(mode);
            std::fs::set_permissions(&tmp_path, perms).map_err(|e| format!("failed to write file: {e}"))?;
        }
        #[cfg(not(unix))]
        let _ = mode;
        Ok(())
    })();

    if let Err(e) = result {
        let _ = std::fs::remove_file(&tmp_path);
        return Err(e);
    }
    std::fs::rename(&tmp_path, path).map_err(|e| {
        let _ = std::fs::remove_file(&tmp_path);
        format!("failed to write file: {e}")
    })
}

fn app_data_dir_of(app: &AppHandle) -> Result<PathBuf, String> {
    app.path().app_data_dir().map_err(|e| format!("could not resolve app data dir: {e}"))
}

// ---------------------------------------------------------------------------
// I/O-bound preflight helpers
// ---------------------------------------------------------------------------

/// Run every declared preflight check for `item` against `profile`'s VM,
/// plus the implicit "compose available" check. Never touches installed
/// instance state; safe to call repeatedly (e.g. from `marketplace_prepare`
/// and standalone `marketplace_preflight`).
async fn run_preflight(state: &AppState, profile: &str, item: &CatalogItem) -> Result<Vec<PreflightResult>, String> {
    let mut results = Vec::new();

    let status = crate::colima::profile_status(profile.to_string()).await?;
    let Some(status) = status else {
        return Err(format!("{profile} is not running — start it first"));
    };

    results.push(evaluate_arch_preflight(&status.arch, &item.architectures));
    if let Some(mem_check) = evaluate_memory_preflight(status.memory, item.min_memory_mb) {
        results.push(mem_check);
    }

    for check in &item.preflight {
        let CatalogPreflightCheck::Sysctl { key, min } = check;
        if !is_valid_sysctl_key(key) {
            results.push(PreflightResult {
                id: format!("sysctl:{key}"),
                ok: false,
                severity: "error".to_string(),
                message: format!("invalid sysctl key in catalog: {key:?}"),
                fixable: false,
            });
            continue;
        }
        let current = exec::run("colima", &["ssh", "-p", profile, "--", "sysctl", "-n", key])
            .await
            .ok()
            .and_then(|out| out.trim().parse::<i64>().ok());
        results.push(evaluate_sysctl_preflight(key, *min, current));
    }

    let socket = resolve_docker_socket(state, profile).await;
    let compose_info = compose::resolve_compose_info(state, profile, &socket).await;
    results.push(evaluate_compose_preflight(compose_info.available));

    Ok(results)
}

#[tauri::command]
pub async fn marketplace_preflight(app: AppHandle, state: State<'_, AppState>, profile: String, item_id: String) -> Result<Vec<PreflightResult>, String> {
    validate_profile_name(&profile)?;
    validate_item_id(&item_id)?;
    let item = find_catalog_item(&app, &item_id).await?;
    run_preflight(&state, &profile, &item).await
}

/// `marketplace_fix_preflight`: apply the fix for one preflight check id.
/// Only `sysctl:<key>` checks are fixable today (§6.8): run `colima ssh -p
/// <p> -- sudo sysctl -w key=value`, then persist it across VM restarts by
/// appending/overwriting the key in `/etc/sysctl.d/99-colima-desktop.conf`
/// inside the VM. Requires re-running `marketplace_preflight` to learn the
/// `min` value again (the check id alone doesn't carry it), so this command
/// takes the full item to look the check back up — but the IPC contract
/// (§6.8) is `profile, checkId` only, so we resolve the min from the
/// currently cached/fetched catalog by scanning every item's preflight list
/// for a `sysctl` check whose key matches `checkId`'s suffix. If multiple
/// catalog items declare the same key with different minimums, the largest
/// minimum wins (the safer value).
#[tauri::command]
pub async fn marketplace_fix_preflight(app: AppHandle, profile: String, check_id: String) -> Result<(), String> {
    validate_profile_name(&profile)?;
    let key = check_id
        .strip_prefix("sysctl:")
        .ok_or_else(|| format!("check {check_id:?} is not fixable"))?;
    if !is_valid_sysctl_key(key) {
        return Err(format!("invalid sysctl key: {key:?}"));
    }

    let catalog = marketplace_catalog(app, false).await?;
    let min = catalog
        .items
        .iter()
        .flat_map(|i| i.preflight.iter())
        .filter_map(|c| {
            let CatalogPreflightCheck::Sysctl { key: k, min } = c;
            (k == key).then_some(*min)
        })
        .max()
        .ok_or_else(|| format!("no catalog item declares a sysctl check for {key}"))?;

    apply_sysctl_fix(&profile, key, min).await
}

/// Apply `colima ssh -p <p> -- sudo sysctl -w key=value`, then persist it in
/// `/etc/sysctl.d/99-colima-desktop.conf` inside the VM. `key` must already
/// be validated against `^[a-z0-9_.]+$`; `min` (an `i64`) is always a
/// digits-only value once formatted, satisfying [`is_valid_sysctl_value`].
async fn apply_sysctl_fix(profile: &str, key: &str, min: i64) -> Result<(), String> {
    if !is_valid_sysctl_key(key) {
        return Err(format!("invalid sysctl key: {key:?}"));
    }
    let value = min.to_string();
    if !is_valid_sysctl_value(&value) {
        return Err(format!("invalid sysctl value for {key}: {value:?}"));
    }

    let assignment = format!("{key}={value}");
    exec::run("colima", &["ssh", "-p", profile, "--", "sudo", "sysctl", "-w", &assignment]).await?;

    // Persist: append (or replace) the line in
    // /etc/sysctl.d/99-colima-desktop.conf so it survives VM restarts. Build
    // the in-VM shell snippet from already-validated key/value only (never
    // from unvalidated catalog/user text) and quote the whole snippet with
    // single quotes for `sh -c`.
    let conf_path = "/etc/sysctl.d/99-colima-desktop.conf";
    let script = format!(
        "touch {conf_path} && (grep -q '^{key}=' {conf_path} && sed -i 's/^{key}=.*/{key}={value}/' {conf_path} || echo '{key}={value}' >> {conf_path})"
    );
    exec::run("colima", &["ssh", "-p", profile, "--", "sudo", "sh", "-c", &script]).await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// marketplace_prepare
// ---------------------------------------------------------------------------

/// Collect the set of host-bound ports currently considered "taken" for a
/// profile: docker-published ports (from `list_containers`) plus ports
/// reserved by other marketplace instances' `.env` files. Does not include
/// the live-bind test, which `resolve_free_port` does per-candidate.
async fn collect_taken_ports(app: &AppHandle, state: &AppState, profile: &str, exclude_project: Option<&str>) -> HashSet<u16> {
    let mut taken = HashSet::new();
    let socket = resolve_docker_socket(state, profile).await;
    if let Ok(stdout) = exec::run("docker", &["-H", &socket, "ps", "-a", "--no-trunc", "--format", "{{json .}}"]).await {
        if let Ok(raw) = exec::parse_json_lines::<RawContainerPorts>(&stdout) {
            for entry in raw {
                taken.extend(crate::docker::parse_port_links(&entry.ports).into_iter().map(|p| p.host_port));
            }
        }
    }
    if let Ok(app_data_dir) = app_data_dir_of(app) {
        let profile_dir = profile_marketplace_dir(&app_data_dir, profile);
        taken.extend(ports_reserved_by_other_instances(&profile_dir, exclude_project));
    }
    taken
}

/// Minimal shape of one `docker ps --format '{{json .}}'` line — just the
/// `Ports` field, for taken-port collection (the full `Container` type and
/// its label-enrichment pass live in `docker.rs` and aren't needed here).
#[derive(Debug, Deserialize)]
struct RawContainerPorts {
    #[serde(rename = "Ports", default)]
    ports: String,
}

#[tauri::command]
pub async fn marketplace_prepare(app: AppHandle, state: State<'_, AppState>, profile: String, item_id: String) -> Result<MarketplacePrepareResponse, String> {
    validate_profile_name(&profile)?;
    validate_item_id(&item_id)?;
    let item = find_catalog_item(&app, &item_id).await?;

    let app_data_dir = app_data_dir_of(&app)?;
    let profile_dir = profile_marketplace_dir(&app_data_dir, &profile);
    let existing_projects = list_instance_project_names(&profile_dir);
    let project_name = default_project_name(&item_id, &existing_projects);

    let mut taken_ports = collect_taken_ports(&app, &state, &profile, None).await;

    let mut variables = Vec::with_capacity(item.variables.len());
    for var in &item.variables {
        let value = match var.var_type.as_str() {
            "password" => generate_password(var.length.unwrap_or(24)),
            "port" => {
                let default_port: u16 = var
                    .default
                    .as_ref()
                    .and_then(|v| v.as_u64())
                    .and_then(|v| u16::try_from(v).ok())
                    .unwrap_or(0);
                let port = resolve_free_port(default_port, &taken_ports);
                taken_ports.insert(port);
                port.to_string()
            }
            _ => var
                .default
                .as_ref()
                .and_then(|v| v.as_str().map(str::to_string))
                .unwrap_or_default(),
        };
        variables.push(RenderedVariable {
            name: var.name.clone(),
            label: var.label.clone().unwrap_or_else(|| var.name.clone()),
            var_type: var.var_type.clone(),
            value,
            hidden: var.hidden,
        });
    }

    let preflight = run_preflight(&state, &profile, &item).await?;

    Ok(MarketplacePrepareResponse { project_name, variables, preflight })
}

/// List every existing instance project directory name under `profile_dir`.
fn list_instance_project_names(profile_dir: &Path) -> HashSet<String> {
    let Ok(entries) = std::fs::read_dir(profile_dir) else {
        return HashSet::new();
    };
    entries
        .flatten()
        .filter(|e| e.file_type().map(|t| t.is_dir()).unwrap_or(false))
        .map(|e| e.file_name().to_string_lossy().to_string())
        .collect()
}

// ---------------------------------------------------------------------------
// marketplace_install
// ---------------------------------------------------------------------------

#[tauri::command]
pub async fn marketplace_install(
    app: AppHandle,
    state: State<'_, AppState>,
    profile: String,
    item_id: String,
    project_name: String,
    values: HashMap<String, String>,
) -> Result<InstalledApp, String> {
    validate_profile_name(&profile)?;
    validate_item_id(&item_id)?;
    compose::validate_project_name(&project_name)?;

    let item = find_catalog_item(&app, &item_id).await?;
    if item.compose.trim().is_empty() {
        return Err(format!("catalog item {item_id} has no compose definition"));
    }

    // Re-validate every declared variable's value (types + port freeness),
    // per §6.8's "re-validate values" instruction.
    let app_data_dir = app_data_dir_of(&app)?;
    let mut taken_ports = collect_taken_ports(&app, &state, &profile, Some(&project_name)).await;

    let mut var_order = Vec::with_capacity(item.variables.len());
    for var in &item.variables {
        var_order.push(var.name.clone());
        let value = values
            .get(&var.name)
            .ok_or_else(|| format!("missing value for variable {}", var.name))?;
        validate_variable_value(var, value)?;
        if var.var_type == "port" {
            let port: u16 = value.parse().map_err(|_| format!("{}: invalid port", var.name))?;
            if !is_port_free(port, &taken_ports) {
                return Err(format!("{}: port {port} is already in use", var.name));
            }
            taken_ports.insert(port);
        }
    }

    let dir = instance_dir_within_root(&app_data_dir, &profile, &project_name)?;
    std::fs::create_dir_all(&dir).map_err(|e| format!("failed to create instance directory: {e}"))?;

    // Write compose.yml verbatim.
    let compose_path = dir.join("compose.yml");
    write_atomically(&compose_path, item.compose.as_bytes(), None)?;

    // Write .env (mode 0600).
    let env_pairs = build_env_pairs(&values, &project_name, &var_order);
    let env_content = serialize_env_file(&env_pairs);
    let env_path = dir.join(".env");
    write_atomically(&env_path, env_content.as_bytes(), Some(0o600))?;

    // Write instance.json.
    let manifest = InstanceManifest {
        item_id: item_id.clone(),
        name: item.name.clone(),
        icon: item.icon.clone(),
        project_name: project_name.clone(),
        created_at: iso_now(),
        catalog_generated_at: String::new(),
        values: values.clone(),
    };
    let manifest_json = serde_json::to_string_pretty(&manifest).map_err(|e| e.to_string())?;
    let manifest_path = dir.join("instance.json");
    write_atomically(&manifest_path, manifest_json.as_bytes(), None)?;

    // compose up -d
    let socket = resolve_docker_socket(&state, &profile).await;
    let mode = require_compose_mode(&state, &profile, &socket).await?;
    let lock_key = format!("compose:{project_name}");
    let _guard = state.try_lock_profile(&lock_key)?;

    let compose_files = vec![compose_path.to_string_lossy().to_string()];
    let (bin, args) = compose::build_up_args(mode, &socket, &compose_files, Some(&project_name), &ComposeUpOptions {
        build: false,
        pull: "missing".to_string(),
        force_recreate: false,
    });
    let arg_refs: Vec<&str> = args.iter().map(String::as_str).collect();
    let env_overrides = compose_env_for_mode(mode, &socket);
    let env_refs: Vec<(&str, &str)> = env_overrides.iter().map(|(k, v)| (k.as_str(), v.as_str())).collect();

    let up_result = exec::run_streaming_with_env(&app, &bin, &arg_refs, &profile, "marketplace-install", &env_refs, Some(&dir)).await;
    let _ = app.emit("profiles-changed", ());
    up_result?;

    // Wait for readiness, emitting progress lines on the same op log.
    let mut warning: Option<String> = None;
    if let Some(ready) = &item.ready {
        emit_op_log(&app, &profile, "marketplace-install", "waiting for the app to become ready…");
        if let Err(timeout_msg) = wait_ready(&app, &profile, &project_name, mode, &socket, ready).await {
            warning = Some(timeout_msg);
        } else {
            emit_op_log(&app, &profile, "marketplace-install", "ready.");
        }
    }

    let status = compose_project_status(&state, &profile, &project_name).await.unwrap_or_else(|| "unknown".to_string());
    let final_status = if warning.is_some() { "starting".to_string() } else { status };

    if let Some(w) = &warning {
        emit_op_log(&app, &profile, "marketplace-install", &format!("warning: {w}"));
    }

    Ok(InstalledApp {
        project_name,
        item_id,
        name: item.name,
        icon: item.icon,
        created_at: manifest.created_at,
        status: final_status,
        endpoints: render_endpoints(&item.endpoints, &values),
        notes: item.notes,
    })
}

fn emit_op_log(app: &AppHandle, profile: &str, op: &str, line: &str) {
    let _ = app.emit(
        "colima-op-log",
        exec::OpLog { profile: profile.to_string(), op: op.to_string(), line: line.to_string() },
    );
}

async fn require_compose_mode(state: &AppState, profile: &str, socket: &str) -> Result<ComposeMode, String> {
    let info = compose::resolve_compose_info(state, profile, socket).await;
    info.mode.ok_or_else(|| "Docker Compose is not available".to_string())
}

fn compose_env_for_mode(mode: ComposeMode, socket: &str) -> Vec<(String, String)> {
    match mode {
        ComposeMode::Plugin => Vec::new(),
        ComposeMode::Standalone => vec![("DOCKER_HOST".to_string(), socket.to_string())],
    }
}

/// Poll the declared readiness condition every 2s until ready or timeout.
/// Returns `Err(message)` on timeout (never on transient poll errors, which
/// are just retried).
async fn wait_ready(app: &AppHandle, profile: &str, project: &str, mode: ComposeMode, socket: &str, ready: &CatalogReady) -> Result<(), String> {
    let timeout_sec = match ready {
        CatalogReady::Http { timeout_sec, .. } => *timeout_sec,
        CatalogReady::Healthy { timeout_sec } => *timeout_sec,
        CatalogReady::Running { timeout_sec } => *timeout_sec,
    };

    let deadline = tokio::time::Instant::now() + Duration::from_secs(timeout_sec);
    let mut elapsed = 0u64;
    loop {
        let is_ready = match ready {
            CatalogReady::Http { url, expect_status, .. } => poll_http_ready(url, expect_status).await,
            CatalogReady::Healthy { .. } => poll_healthy_ready(mode, socket, project).await,
            CatalogReady::Running { .. } => poll_running_ready(mode, socket, project).await,
        };
        if is_ready {
            return Ok(());
        }
        if tokio::time::Instant::now() >= deadline {
            return Err(format!("timed out after {timeout_sec}s waiting for readiness"));
        }
        tokio::time::sleep(Duration::from_secs(2)).await;
        elapsed += 2;
        emit_op_log(app, profile, "marketplace-install", &format!("still waiting for {project} to become ready… ({elapsed}s)"));
    }
}

async fn poll_http_ready(url: &str, expect: &[u16]) -> bool {
    let client = match reqwest::Client::builder().timeout(Duration::from_secs(5)).build() {
        Ok(c) => c,
        Err(_) => return false,
    };
    match client.get(url).send().await {
        Ok(resp) => http_status_is_ready(resp.status().as_u16(), expect),
        Err(_) => false,
    }
}

async fn poll_healthy_ready(mode: ComposeMode, socket: &str, project: &str) -> bool {
    let statuses = compose_ps_health(mode, socket, project).await;
    evaluate_healthy_ready(&statuses)
}

async fn poll_running_ready(mode: ComposeMode, socket: &str, project: &str) -> bool {
    let status = compose_project_status_raw(mode, socket, project).await;
    status.map(|s| s.to_lowercase().contains("running")).unwrap_or(false)
}

#[derive(Debug, Deserialize)]
struct RawComposePsEntry {
    #[serde(default)]
    #[serde(rename = "Health")]
    health: Option<String>,
}

/// `compose -p <project> ps --format json`'s per-service `Health` field for
/// every service (empty string when no healthcheck is defined, mapped to
/// `None`).
async fn compose_ps_health(mode: ComposeMode, socket: &str, project: &str) -> Vec<Option<String>> {
    let bin = match mode {
        ComposeMode::Plugin => "docker",
        ComposeMode::Standalone => "docker-compose",
    };
    let mut args: Vec<String> = match mode {
        ComposeMode::Plugin => vec!["-H".to_string(), socket.to_string(), "compose".to_string()],
        ComposeMode::Standalone => Vec::new(),
    };
    args.push("-p".to_string());
    args.push(project.to_string());
    args.push("ps".to_string());
    args.push("--format".to_string());
    args.push("json".to_string());
    let arg_refs: Vec<&str> = args.iter().map(String::as_str).collect();
    let stdout = match mode {
        ComposeMode::Plugin => exec::run(bin, &arg_refs).await,
        ComposeMode::Standalone => exec::run_with_env(bin, &arg_refs, &[("DOCKER_HOST", socket)]).await,
    };
    let Ok(stdout) = stdout else { return Vec::new() };
    let entries: Vec<RawComposePsEntry> = exec::parse_json_lines_or_array(&stdout).unwrap_or_default();
    entries
        .into_iter()
        .map(|e| e.health.filter(|h| !h.is_empty()))
        .collect()
}

async fn compose_project_status_raw(mode: ComposeMode, socket: &str, project: &str) -> Option<String> {
    let bin = match mode {
        ComposeMode::Plugin => "docker",
        ComposeMode::Standalone => "docker-compose",
    };
    let mut args: Vec<String> = match mode {
        ComposeMode::Plugin => vec!["-H".to_string(), socket.to_string(), "compose".to_string()],
        ComposeMode::Standalone => Vec::new(),
    };
    args.push("ls".to_string());
    args.push("-a".to_string());
    args.push("--format".to_string());
    args.push("json".to_string());
    let arg_refs: Vec<&str> = args.iter().map(String::as_str).collect();
    let stdout = match mode {
        ComposeMode::Plugin => exec::run(bin, &arg_refs).await,
        ComposeMode::Standalone => exec::run_with_env(bin, &arg_refs, &[("DOCKER_HOST", socket)]).await,
    }
    .ok()?;
    let projects = compose::parse_compose_projects(&stdout).ok()?;
    projects.into_iter().find(|p| p.name == project).map(|p| p.status)
}

/// `compose_projects`-style status lookup for one project, used by
/// `marketplace_install`/`marketplace_installed` ("missing" if not found).
async fn compose_project_status(state: &AppState, profile: &str, project: &str) -> Option<String> {
    let socket = resolve_docker_socket(state, profile).await;
    let mode = compose::resolve_compose_info(state, profile, &socket).await.mode?;
    compose_project_status_raw(mode, &socket, project).await
}

// ---------------------------------------------------------------------------
// marketplace_installed
// ---------------------------------------------------------------------------

#[tauri::command]
pub async fn marketplace_installed(app: AppHandle, state: State<'_, AppState>, profile: String) -> Result<Vec<InstalledApp>, String> {
    validate_profile_name(&profile)?;
    let app_data_dir = app_data_dir_of(&app)?;
    let profile_dir = profile_marketplace_dir(&app_data_dir, &profile);

    let Ok(entries) = std::fs::read_dir(&profile_dir) else {
        return Ok(Vec::new());
    };

    let socket = resolve_docker_socket(&state, &profile).await;
    let mode = compose::resolve_compose_info(&state, &profile, &socket).await.mode;

    let mut projects_by_name: HashMap<String, String> = HashMap::new();
    if let Some(mode) = mode {
        let bin = match mode {
            ComposeMode::Plugin => "docker",
            ComposeMode::Standalone => "docker-compose",
        };
        let mut args: Vec<String> = match mode {
            ComposeMode::Plugin => vec!["-H".to_string(), socket.clone(), "compose".to_string()],
            ComposeMode::Standalone => Vec::new(),
        };
        args.push("ls".to_string());
        args.push("-a".to_string());
        args.push("--format".to_string());
        args.push("json".to_string());
        let arg_refs: Vec<&str> = args.iter().map(String::as_str).collect();
        let stdout = match mode {
            ComposeMode::Plugin => exec::run(bin, &arg_refs).await,
            ComposeMode::Standalone => exec::run_with_env(bin, &arg_refs, &[("DOCKER_HOST", &socket)]).await,
        };
        if let Ok(stdout) = stdout {
            if let Ok(projects) = compose::parse_compose_projects(&stdout) {
                for p in projects {
                    projects_by_name.insert(p.name, p.status);
                }
            }
        }
    }

    let mut apps = Vec::new();
    for entry in entries.flatten() {
        if !entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
            continue;
        }
        let manifest_path = entry.path().join("instance.json");
        let Ok(content) = std::fs::read_to_string(&manifest_path) else { continue };
        let Ok(manifest): Result<InstanceManifest, _> = serde_json::from_str(&content) else { continue };

        // Try to resolve endpoints/notes from the currently-known catalog
        // item; if the item has since disappeared from the catalog, fall
        // back to rendering with no endpoints rather than failing the whole
        // list.
        let (endpoints, notes) = match find_catalog_item(&app, &manifest.item_id).await {
            Ok(item) => (render_endpoints(&item.endpoints, &manifest.values), item.notes),
            Err(_) => (Vec::new(), None),
        };

        let status = projects_by_name.get(&manifest.project_name).cloned().unwrap_or_else(|| "missing".to_string());

        apps.push(InstalledApp {
            project_name: manifest.project_name,
            item_id: manifest.item_id,
            name: manifest.name,
            icon: manifest.icon,
            created_at: manifest.created_at,
            status,
            endpoints,
            notes,
        });
    }

    apps.sort_by(|a, b| a.created_at.cmp(&b.created_at));
    Ok(apps)
}

// ---------------------------------------------------------------------------
// marketplace_uninstall
// ---------------------------------------------------------------------------

#[tauri::command]
pub async fn marketplace_uninstall(
    app: AppHandle,
    state: State<'_, AppState>,
    profile: String,
    project_name: String,
    remove_volumes: bool,
) -> Result<(), String> {
    validate_profile_name(&profile)?;
    compose::validate_project_name(&project_name)?;

    let app_data_dir = app_data_dir_of(&app)?;
    let dir = instance_dir_within_root(&app_data_dir, &profile, &project_name)?;

    if dir.is_dir() {
        let socket = resolve_docker_socket(&state, &profile).await;
        if let Some(mode) = compose::resolve_compose_info(&state, &profile, &socket).await.mode {
            let lock_key = format!("compose:{project_name}");
            let _guard = state.try_lock_profile(&lock_key)?;

            let compose_path = dir.join("compose.yml");
            let config_files = if compose_path.is_file() {
                vec![compose_path.to_string_lossy().to_string()]
            } else {
                Vec::new()
            };
            if let Ok((bin, args)) = compose::build_action_args(mode, &socket, &project_name, "down", &config_files, remove_volumes) {
                let arg_refs: Vec<&str> = args.iter().map(String::as_str).collect();
                let env_overrides = compose_env_for_mode(mode, &socket);
                let env_refs: Vec<(&str, &str)> = env_overrides.iter().map(|(k, v)| (k.as_str(), v.as_str())).collect();
                let _ = exec::run_streaming_with_env(&app, &bin, &arg_refs, &profile, "marketplace-uninstall", &env_refs, Some(&dir)).await;
            }
        }
    }

    // Remove the instance dir — guarded above to stay within the
    // marketplace root for this profile.
    if dir.exists() {
        std::fs::remove_dir_all(&dir).map_err(|e| format!("failed to remove instance directory: {e}"))?;
    }

    let _ = app.emit("profiles-changed", ());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    // -- item id validation --

    #[test]
    fn item_id_validation() {
        assert!(is_valid_item_id("elasticsearch-kibana"));
        assert!(is_valid_item_id("postgres"));
        assert!(is_valid_item_id("a1"));
        assert!(!is_valid_item_id(""));
        assert!(!is_valid_item_id("Elastic"));
        assert!(!is_valid_item_id("-leading"));
        assert!(!is_valid_item_id("has space"));
        assert!(!is_valid_item_id("has_underscore"));
    }

    // -- default project name --

    #[test]
    fn default_project_name_uses_cd_prefix() {
        let taken = HashSet::new();
        assert_eq!(default_project_name("mailpit", &taken), "cd-mailpit");
    }

    #[test]
    fn default_project_name_suffixes_when_taken() {
        let mut taken = HashSet::new();
        taken.insert("cd-mailpit".to_string());
        assert_eq!(default_project_name("mailpit", &taken), "cd-mailpit-2");
        taken.insert("cd-mailpit-2".to_string());
        assert_eq!(default_project_name("mailpit", &taken), "cd-mailpit-3");
    }

    // -- template rendering --

    #[test]
    fn render_template_substitutes_known_vars() {
        let mut values = HashMap::new();
        values.insert("PORT".to_string(), "9200".to_string());
        let out = render_template("http://localhost:${PORT}", &values);
        assert_eq!(out, "http://localhost:9200");
    }

    #[test]
    fn render_template_leaves_unknown_vars_untouched() {
        let values = HashMap::new();
        let out = render_template("http://localhost:${MISSING}", &values);
        assert_eq!(out, "http://localhost:${MISSING}");
    }

    #[test]
    fn render_template_multiple_vars() {
        let mut values = HashMap::new();
        values.insert("USER".to_string(), "app".to_string());
        values.insert("PASS".to_string(), "secret".to_string());
        values.insert("PORT".to_string(), "5432".to_string());
        let out = render_template("postgres://${USER}:${PASS}@localhost:${PORT}/app", &values);
        assert_eq!(out, "postgres://app:secret@localhost:5432/app");
    }

    #[test]
    fn render_template_unterminated_brace_left_as_is() {
        let values = HashMap::new();
        let out = render_template("no closing ${BRACE", &values);
        assert_eq!(out, "no closing ${BRACE");
    }

    #[test]
    fn render_template_no_placeholders() {
        let values = HashMap::new();
        assert_eq!(render_template("plain text", &values), "plain text");
    }

    // -- password generation --

    #[test]
    fn generate_password_has_requested_length_and_alphanumeric() {
        let pw = generate_password(24);
        assert_eq!(pw.len(), 24);
        assert!(pw.chars().all(|c| c.is_ascii_alphanumeric()));
    }

    #[test]
    fn generate_password_is_random_across_calls() {
        let a = generate_password(32);
        let b = generate_password(32);
        assert_ne!(a, b);
    }

    #[test]
    fn generate_password_minimum_length_one() {
        let pw = generate_password(0);
        assert_eq!(pw.len(), 1);
    }

    // -- port selection --

    #[test]
    fn is_port_free_basic() {
        let mut taken = HashSet::new();
        taken.insert(8080);
        assert!(!is_port_free(8080, &taken));
        assert!(is_port_free(8081, &taken));
    }

    #[test]
    fn resolve_free_port_prefers_default() {
        let taken = HashSet::new();
        // Use an unusual high port unlikely to be bound in CI.
        let port = resolve_free_port(58001, &taken);
        assert_eq!(port, 58001);
    }

    #[test]
    fn resolve_free_port_scans_upward_past_taken_set() {
        let mut taken = HashSet::new();
        taken.insert(58101);
        taken.insert(58102);
        let port = resolve_free_port(58101, &taken);
        assert_eq!(port, 58103);
    }

    // -- value validation --

    #[test]
    fn validate_variable_value_port_accepts_valid() {
        let var = CatalogVariable {
            name: "P".to_string(),
            var_type: "port".to_string(),
            label: None,
            length: None,
            default: None,
            hidden: false,
        };
        assert!(validate_variable_value(&var, "8080").is_ok());
        assert!(validate_variable_value(&var, "not-a-port").is_err());
        assert!(validate_variable_value(&var, "99999999").is_err());
    }

    #[test]
    fn validate_variable_value_password_rejects_non_alphanumeric() {
        let var = CatalogVariable {
            name: "PW".to_string(),
            var_type: "password".to_string(),
            label: None,
            length: None,
            default: None,
            hidden: false,
        };
        assert!(validate_variable_value(&var, "abc123").is_ok());
        assert!(validate_variable_value(&var, "abc-123!").is_err());
        assert!(validate_variable_value(&var, "").is_err());
    }

    #[test]
    fn validate_variable_value_string_accepts_anything() {
        let var = CatalogVariable {
            name: "S".to_string(),
            var_type: "string".to_string(),
            label: None,
            length: None,
            default: None,
            hidden: false,
        };
        assert!(validate_variable_value(&var, "anything at all!").is_ok());
    }

    #[test]
    fn validate_variable_value_unknown_type_errors() {
        let var = CatalogVariable {
            name: "X".to_string(),
            var_type: "bogus".to_string(),
            label: None,
            length: None,
            default: None,
            hidden: false,
        };
        assert!(validate_variable_value(&var, "x").is_err());
    }

    // -- env file serialisation --

    #[test]
    fn env_serialization_roundtrip_basic_values() {
        let pairs = vec![("USER".to_string(), "app".to_string()), ("PASS".to_string(), "s3cret".to_string())];
        let content = serialize_env_file(&pairs);
        let parsed = parse_env_lines(&content);
        assert_eq!(parsed, pairs);
    }

    #[test]
    fn env_serialization_escapes_quotes_and_backslashes() {
        let pairs = vec![("VAL".to_string(), "has \"quotes\" and \\backslash".to_string())];
        let content = serialize_env_file(&pairs);
        let parsed = parse_env_lines(&content);
        assert_eq!(parsed, pairs);
    }

    #[test]
    fn env_serialization_handles_empty_value() {
        let pairs = vec![("EMPTY".to_string(), String::new())];
        let content = serialize_env_file(&pairs);
        let parsed = parse_env_lines(&content);
        assert_eq!(parsed, pairs);
    }

    #[test]
    fn env_serialization_ignores_comments_and_blank_lines() {
        let content = "# a comment\n\nKEY=\"value\"\n";
        let parsed = parse_env_lines(content);
        assert_eq!(parsed, vec![("KEY".to_string(), "value".to_string())]);
    }

    #[test]
    fn build_env_pairs_includes_compose_project_name() {
        let mut values = HashMap::new();
        values.insert("PORT".to_string(), "8080".to_string());
        let pairs = build_env_pairs(&values, "cd-app", &["PORT".to_string()]);
        assert_eq!(pairs, vec![("PORT".to_string(), "8080".to_string()), ("COMPOSE_PROJECT_NAME".to_string(), "cd-app".to_string())]);
    }

    #[test]
    fn build_env_pairs_preserves_var_order() {
        let mut values = HashMap::new();
        values.insert("B".to_string(), "2".to_string());
        values.insert("A".to_string(), "1".to_string());
        let pairs = build_env_pairs(&values, "proj", &["A".to_string(), "B".to_string()]);
        assert_eq!(pairs[0].0, "A");
        assert_eq!(pairs[1].0, "B");
    }

    // -- preflight evaluation --

    #[test]
    fn arch_preflight_ok_when_supported() {
        let architectures = vec!["arm64".to_string(), "amd64".to_string()];
        let result = evaluate_arch_preflight("aarch64", &architectures);
        assert!(result.ok);
        assert_eq!(result.severity, "error");
    }

    #[test]
    fn arch_preflight_fails_when_unsupported() {
        let architectures = vec!["amd64".to_string()];
        let result = evaluate_arch_preflight("aarch64", &architectures);
        assert!(!result.ok);
    }

    #[test]
    fn arch_preflight_ok_when_no_restriction() {
        let result = evaluate_arch_preflight("aarch64", &[]);
        assert!(result.ok);
    }

    #[test]
    fn normalize_arch_mapping() {
        assert_eq!(normalize_arch("aarch64"), "arm64");
        assert_eq!(normalize_arch("x86_64"), "amd64");
        assert_eq!(normalize_arch("other"), "other");
    }

    #[test]
    fn memory_preflight_warns_when_below_minimum() {
        let result = evaluate_memory_preflight(1024 * 1024 * 1024, Some(3072)).unwrap();
        assert!(!result.ok);
        assert_eq!(result.severity, "warning");
    }

    #[test]
    fn memory_preflight_ok_when_sufficient() {
        let result = evaluate_memory_preflight(4096 * 1024 * 1024, Some(3072)).unwrap();
        assert!(result.ok);
    }

    #[test]
    fn memory_preflight_none_when_not_declared() {
        assert!(evaluate_memory_preflight(1024, None).is_none());
    }

    #[test]
    fn sysctl_preflight_ok_when_at_or_above_min() {
        let result = evaluate_sysctl_preflight("vm.max_map_count", 262144, Some(262144));
        assert!(result.ok);
        assert!(result.fixable);
    }

    #[test]
    fn sysctl_preflight_fails_when_below_min() {
        let result = evaluate_sysctl_preflight("vm.max_map_count", 262144, Some(65530));
        assert!(!result.ok);
        assert!(result.fixable);
    }

    #[test]
    fn sysctl_preflight_fails_when_unreadable() {
        let result = evaluate_sysctl_preflight("vm.max_map_count", 262144, None);
        assert!(!result.ok);
    }

    #[test]
    fn compose_preflight_reflects_availability() {
        assert!(evaluate_compose_preflight(true).ok);
        assert!(!evaluate_compose_preflight(false).ok);
    }

    // -- ready-condition evaluation --

    #[test]
    fn http_status_ready_matches_expect_list() {
        assert!(http_status_is_ready(200, &[200, 401]));
        assert!(http_status_is_ready(401, &[200, 401]));
        assert!(!http_status_is_ready(500, &[200, 401]));
    }

    #[test]
    fn healthy_ready_all_healthy() {
        let statuses = vec![Some("healthy".to_string()), Some("healthy".to_string())];
        assert!(evaluate_healthy_ready(&statuses));
    }

    #[test]
    fn healthy_ready_one_unhealthy_blocks() {
        let statuses = vec![Some("healthy".to_string()), Some("starting".to_string())];
        assert!(!evaluate_healthy_ready(&statuses));
    }

    #[test]
    fn healthy_ready_no_healthchecks_defined_is_ready() {
        let statuses = vec![None, None];
        assert!(evaluate_healthy_ready(&statuses));
    }

    #[test]
    fn healthy_ready_empty_list_not_ready() {
        assert!(!evaluate_healthy_ready(&[]));
    }

    // -- sysctl key/value validation --

    #[test]
    fn sysctl_key_validation() {
        assert!(is_valid_sysctl_key("vm.max_map_count"));
        assert!(is_valid_sysctl_key("net.core.somaxconn"));
        assert!(!is_valid_sysctl_key("vm.max map count"));
        assert!(!is_valid_sysctl_key("VM.MAX"));
        assert!(!is_valid_sysctl_key(""));
        assert!(!is_valid_sysctl_key("rm -rf /"));
    }

    #[test]
    fn sysctl_value_validation() {
        assert!(is_valid_sysctl_value("262144"));
        assert!(!is_valid_sysctl_value("262144; rm -rf /"));
        assert!(!is_valid_sysctl_value(""));
        assert!(!is_valid_sysctl_value("-1"));
    }

    // -- instance dir traversal guard --

    #[test]
    fn instance_dir_within_root_rejects_traversal_project_name() {
        let app_data = PathBuf::from("/tmp/appdata");
        let result = instance_dir_within_root(&app_data, "default", "../../etc");
        assert!(result.is_err());
    }

    #[test]
    fn instance_dir_within_root_accepts_valid_project() {
        let app_data = PathBuf::from("/tmp/appdata");
        let result = instance_dir_within_root(&app_data, "default", "cd-mailpit").unwrap();
        assert_eq!(result, PathBuf::from("/tmp/appdata/marketplace/default/cd-mailpit"));
    }

    // -- catalog parsing --

    #[test]
    fn parse_catalog_rejects_unsupported_schema_version() {
        let json = r#"{"schemaVersion":2,"generatedAt":"now","items":[]}"#;
        assert!(parse_catalog(json).is_none());
    }

    #[test]
    fn parse_catalog_accepts_supported_schema_version() {
        let json = r#"{"schemaVersion":1,"generatedAt":"now","items":[]}"#;
        assert_eq!(parse_catalog(json).unwrap().len(), 0);
    }

    #[test]
    fn placeholder_builtin_catalog_parses() {
        // The committed catalog/dist/catalog.json placeholder (or the real
        // one, once the catalog agent's build has run) must always parse.
        let items = builtin_catalog_items();
        // Empty is fine (placeholder); just assert parsing didn't blow up
        // and, if non-empty, every item has a non-empty id.
        for item in &items {
            assert!(!item.id.is_empty());
        }
    }

    // -- wire-format compatibility with src/lib/types.ts's CatalogItem/
    // MarketplaceReadySpec/MarketplacePreflightSpec (§6.8) --

    #[test]
    fn catalog_item_wire_shape_matches_frontend_types() {
        // Mirrors the shape mock.ts's `mockCatalogItems[0]` (elasticsearch-kibana)
        // uses, including the `minMemoryMB` acronym casing and the `type`-tagged
        // ready/preflight enums.
        let json = r#"{
            "id": "elasticsearch-kibana",
            "name": "Elasticsearch + Kibana",
            "description": "desc",
            "category": "search",
            "tags": ["elk"],
            "icon": "elasticsearch",
            "website": "https://www.elastic.co",
            "source": {"name": "docker/awesome-compose", "url": "https://x", "license": "CC0-1.0"},
            "architectures": ["amd64", "arm64"],
            "minMemoryMB": 3072,
            "variables": [{"name": "ELASTIC_PASSWORD", "type": "password", "label": "pw", "length": 24}],
            "endpoints": [{"name": "Kibana", "url": "http://localhost:${KIBANA_PORT}", "primary": true}],
            "preflight": [{"type": "sysctl", "key": "vm.max_map_count", "min": 262144}],
            "ready": {"type": "http", "url": "http://x", "expectStatus": [200, 401], "timeoutSec": 240},
            "notes": "n",
            "compose": "services: {}"
        }"#;
        let item: CatalogItem = serde_json::from_str(json).expect("should parse the real app.json shape");
        assert_eq!(item.min_memory_mb, Some(3072));
        assert_eq!(item.variables[0].var_type, "password");

        // Round-trip the field name: `minMemoryMB`, not serde's default
        // `minMemoryMb`.
        let reserialized = serde_json::to_value(&item).unwrap();
        assert!(reserialized.get("minMemoryMB").is_some(), "{reserialized}");
        assert!(reserialized.get("minMemoryMb").is_none(), "{reserialized}");

        match &item.preflight[0] {
            CatalogPreflightCheck::Sysctl { key, min } => {
                assert_eq!(key, "vm.max_map_count");
                assert_eq!(*min, 262144);
            }
        }
        match &item.ready {
            Some(CatalogReady::Http { url, expect_status, timeout_sec }) => {
                assert_eq!(url, "http://x");
                assert_eq!(expect_status, &vec![200, 401]);
                assert_eq!(*timeout_sec, 240);
            }
            other => panic!("expected Http ready, got {other:?}"),
        }
    }

    #[test]
    fn catalog_ready_serializes_with_type_tag_camel_case() {
        let ready = CatalogReady::Healthy { timeout_sec: 120 };
        let json = serde_json::to_value(&ready).unwrap();
        assert_eq!(json["type"], "healthy");
        assert_eq!(json["timeoutSec"], 120);
    }

    // -- render_endpoints --

    #[test]
    fn render_endpoints_substitutes_all_templated_fields() {
        let mut values = HashMap::new();
        values.insert("PORT".to_string(), "9200".to_string());
        values.insert("PASS".to_string(), "s3cr3t".to_string());
        let endpoints = vec![CatalogEndpoint {
            name: "API".to_string(),
            url: Some("http://localhost:${PORT}".to_string()),
            value: None,
            username: Some("elastic".to_string()),
            password: Some("${PASS}".to_string()),
            primary: true,
        }];
        let rendered = render_endpoints(&endpoints, &values);
        assert_eq!(rendered[0].url.as_deref(), Some("http://localhost:9200"));
        assert_eq!(rendered[0].password.as_deref(), Some("s3cr3t"));
        assert_eq!(rendered[0].username.as_deref(), Some("elastic"));
        assert!(rendered[0].primary);
    }
}

/// Live end-to-end diagnostic against this machine's real colima (profile
/// `default`). Ignored by default: `cargo test live_marketplace_install_and_uninstall
/// -- --ignored --nocapture`.
///
/// Colima's `default` profile may be stopped on the machine running this
/// test — if so, the test prints a message and returns early rather than
/// starting/stopping colima itself (never do that from a test, per
/// AGENTS.md). If running, it installs a light built-in catalog item
/// (preferring `mailpit` if present, else the first item with an `http`
/// ready check) into a scratch `<app_data_dir>/marketplace/default/` under a
/// throwaway app-data directory, waits for its primary endpoint to answer
/// 200, then uninstalls with `removeVolumes: true`. It only ever touches
/// compose projects named `cd-livetest-*`, mirroring `compose.rs`'s
/// `live_compose_up_and_down`, and calls the underlying async helpers
/// directly (no `AppHandle`/`State` mock harness exists in this crate).
#[cfg(test)]
mod live_tests {
    use super::*;

    async fn colima_default_running() -> bool {
        matches!(
            exec::run("colima", &["status", "--json", "-p", "default"]).await,
            Ok(stdout) if serde_json::from_str::<serde_json::Value>(stdout.trim()).is_ok()
        )
    }

    #[tokio::test]
    #[ignore]
    async fn live_marketplace_install_and_uninstall() {
        if !colima_default_running().await {
            println!("colima profile `default` is not running — skipping live marketplace test");
            return;
        }

        let items = builtin_catalog_items();
        if items.is_empty() {
            println!("built-in catalog is empty (placeholder not yet replaced by the catalog build) — skipping");
            return;
        }
        let item = items
            .iter()
            .find(|i| i.id == "mailpit")
            .or_else(|| items.iter().find(|i| matches!(i.ready, Some(CatalogReady::Http { .. })) && !i.compose.trim().is_empty()))
            .expect("expected at least one http-ready catalog item for the live test");
        println!("using catalog item: {}", item.id);

        let profile = "default";
        let state = AppState::default();
        let socket = resolve_docker_socket(&state, profile).await;
        let mode = compose::resolve_compose_info(&state, profile, &socket)
            .await
            .mode
            .expect("docker compose must be available on this machine");

        let scratch_app_data = std::env::temp_dir().join(format!(
            "colima-desktop-live-marketplace-{}-{}",
            std::process::id(),
            std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()
        ));
        let project = "cd-livetest-marketplace".to_string();
        let dir = instance_dir(&scratch_app_data, profile, &project);

        // Clean slate: bring down any leftover project with this name.
        if let Ok((down_bin, down_args)) = compose::build_action_args(mode, &socket, &project, "down", &[], true) {
            let down_arg_refs: Vec<&str> = down_args.iter().map(String::as_str).collect();
            let env = compose_env_for_mode(mode, &socket);
            let env_refs: Vec<(&str, &str)> = env.iter().map(|(k, v)| (k.as_str(), v.as_str())).collect();
            match mode {
                ComposeMode::Plugin => {
                    let _ = exec::run(&down_bin, &down_arg_refs).await;
                }
                ComposeMode::Standalone => {
                    let _ = exec::run_with_env(&down_bin, &down_arg_refs, &env_refs).await;
                }
            }
        }

        // Render values: passwords + a high scratch port range unlikely to
        // collide, deterministic ports picked the same way `marketplace_prepare` does.
        let mut values: HashMap<String, String> = HashMap::new();
        let mut var_order = Vec::new();
        let mut taken_ports = HashSet::new();
        for var in &item.variables {
            var_order.push(var.name.clone());
            let value = match var.var_type.as_str() {
                "password" => generate_password(var.length.unwrap_or(24)),
                "port" => {
                    let default_port: u16 = var.default.as_ref().and_then(|v| v.as_u64()).and_then(|v| u16::try_from(v).ok()).unwrap_or(18025);
                    let port = resolve_free_port(default_port, &taken_ports);
                    taken_ports.insert(port);
                    port.to_string()
                }
                _ => var.default.as_ref().and_then(|v| v.as_str().map(str::to_string)).unwrap_or_default(),
            };
            values.insert(var.name.clone(), value);
        }
        println!("rendered {} variable(s) for {}", values.len(), item.id);

        // Write compose.yml + .env (mirrors marketplace_install).
        std::fs::create_dir_all(&dir).unwrap();
        let compose_path = dir.join("compose.yml");
        write_atomically(&compose_path, item.compose.as_bytes(), None).expect("write compose.yml");
        let env_pairs = build_env_pairs(&values, &project, &var_order);
        let env_content = serialize_env_file(&env_pairs);
        write_atomically(&dir.join(".env"), env_content.as_bytes(), Some(0o600)).expect("write .env");

        // compose up -d
        let compose_files = vec![compose_path.to_string_lossy().to_string()];
        let (bin, args) = compose::build_up_args(
            mode,
            &socket,
            &compose_files,
            Some(&project),
            &ComposeUpOptions { build: false, pull: "missing".to_string(), force_recreate: false },
        );
        let arg_refs: Vec<&str> = args.iter().map(String::as_str).collect();
        let env = compose_env_for_mode(mode, &socket);
        let env_refs: Vec<(&str, &str)> = env.iter().map(|(k, v)| (k.as_str(), v.as_str())).collect();
        let up_result = match mode {
            ComposeMode::Plugin => exec::run(&bin, &arg_refs).await,
            ComposeMode::Standalone => exec::run_with_env(&bin, &arg_refs, &env_refs).await,
        };
        up_result.expect("compose up should succeed for the live-test item");
        println!("compose up succeeded for project {project}");

        // Wait for the primary endpoint to answer, using the same
        // ready-condition evaluation as `marketplace_install`.
        if let Some(ready) = &item.ready {
            let deadline = tokio::time::Instant::now()
                + Duration::from_secs(match ready {
                    CatalogReady::Http { timeout_sec, .. } => *timeout_sec,
                    CatalogReady::Healthy { timeout_sec } => *timeout_sec,
                    CatalogReady::Running { timeout_sec } => *timeout_sec,
                });
            loop {
                let is_ready = match ready {
                    CatalogReady::Http { url, expect_status, .. } => poll_http_ready(&render_template(url, &values), expect_status).await,
                    CatalogReady::Healthy { .. } => poll_healthy_ready(mode, &socket, &project).await,
                    CatalogReady::Running { .. } => poll_running_ready(mode, &socket, &project).await,
                };
                if is_ready {
                    break;
                }
                assert!(tokio::time::Instant::now() < deadline, "timed out waiting for {} to become ready", item.id);
                tokio::time::sleep(Duration::from_secs(2)).await;
            }
        }
        println!("{} became ready", item.id);

        let endpoints = render_endpoints(&item.endpoints, &values);
        let primary = endpoints.iter().find(|e| e.primary).or_else(|| endpoints.first());
        if let Some(primary) = primary {
            if let Some(url) = &primary.url {
                let client = reqwest::Client::builder().timeout(Duration::from_secs(10)).build().unwrap();
                let resp = client.get(url).send().await.expect("primary endpoint should respond");
                assert!(resp.status().is_success() || resp.status().as_u16() < 500, "expected a non-5xx response from {url}, got {}", resp.status());
                println!("GET {url} -> {}", resp.status());
            }
        }

        // Uninstall: compose down -v --remove-orphans, then remove the
        // instance dir (mirrors marketplace_uninstall).
        let (down_bin, down_args) = compose::build_action_args(mode, &socket, &project, "down", &compose_files, true).unwrap();
        let down_arg_refs: Vec<&str> = down_args.iter().map(String::as_str).collect();
        let down_result = match mode {
            ComposeMode::Plugin => exec::run(&down_bin, &down_arg_refs).await,
            ComposeMode::Standalone => exec::run_with_env(&down_bin, &down_arg_refs, &env_refs).await,
        };
        down_result.expect("compose down should succeed");
        std::fs::remove_dir_all(&dir).ok();
        std::fs::remove_dir_all(&scratch_app_data).ok();
        println!("cd-livetest-marketplace uninstalled and scratch dir removed");
    }
}
